---
- name: Install packages
  yay:
    packages:
      - networkmanager                  #
      - networkmanager-openvpn          #
      - iw                              #
      - wpa_supplicant                  #