---
- name: Setup system
  hosts: localhost
  connection: local
  roles:
    - ruby
    - mongodb
    - picom
    - audio
    - spotify
    - security
    - x11
    - wm_awesome
    - fonts
    - shell_zsh
    - terminal_kitty
    - vc_git
    - terminal_extras
    - editor_neovim
    - filesystems
    - devops
  tasks:
    - name: Fix resolv.conf so it uses systemd resolvers
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link

    - name: Install unsorted software
      aur:
        name:
          - slack-desktop               # slack client for linux
          - firefox                     # Firefox browser
          - google-chrome               # Chrome browser
          - gparted                     # partition manager
          - htop                        # Improved system resource management from a terminal

          - mariadb                     # MySQL-compatible alternative
          - postgresql                  # PostgreSQL database server software
          - plymouth                    # Splash screen functionality on boot
          - feh                         # CLI based wallpaper tool
          - sddm                        # simple desktop manager (login screen)
          - openvpn                     # OpenVPN client
          - gnu-netcat                  # Provides GNU's NetCat util. (alternatively: openbsd-netcat
          - obs-studio                  # Screencast/streaming software
          - fzf                         # The #1 fuzzy finder
          - highlight                   #
          - task-spooler                #
          - wrk                         # api/website stress-testing
          - wget                        #
          - curl                        #
          - flameshot                   #
          - emacs                       # The operating system with a built-in text editor!
          - visual-studio-code-bin      # The official VS Code builds from MS