---
- name: Install packages
  yay:
    packages:
      - remmina                         # Remote Desktop
      - azure-cli                       # CLI and Rest Interface for Azure Portal
      - powershell-bin                  # PowerShell on Linux
      - 1password-cli                   # 1Password CLI tool