---
- name: Install packages
  aur:
    name:
      - iptables        # Firewall support used by Docker
      - docker          # What if we virtualized the virtualization layer?
      - lens-bin        # The Kubernetes IDE
      - remmina         # Remote Desktop