---
- name: Install packages
  yay:
    packages: zsh
- name: zshenv file
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/zshenv"
    dest: ${HOME}/.zshenv
- name: zsh directory
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/zsh"
    dest: ${HOME}/.config/zsh
# TODO: Figure out why this command silently fails without actually changing the shell
# - name: Set ZSH as the default shell
#   ansible.builtin.command:
#     cmd: chsh -s /usr/bin/zsh