---
- name: Install packages
  yay:
    packages:
      - picom
- name: Ensure config folder exists
  ansible.builtin.file:
    state: directory
    path: ${HOME}/.config/picom/
- name: Copy configuration files
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/picom.conf"
    dest: ${HOME}/.config/picom/picom.conf