---
- name: Install package
  yay:
    packages:
      - git                             # The One True VCS
      - gitui-git                      # Terminal UI for interacting with Git repositories
- name: Copy configuration
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/git"
    dest: ${HOME}/.config/git