---
- name: Install packages
  yay:
    packages:
      - spotify                         # Spotify official client
      - spotifyd                        # Audio daemon for spotify. Lightweight device you can play tunes from.
      - spotify-tui                     # Terminal UI frontend for spotifyd. Requires Spotify API key and a premium account to use.
- name: Ensure user's systemd folder exists
  ansible.builtin.file:
    state: directory
    path: ${HOME}/.config/systemd/user/
- name: Create spotifyd daemon file for systemd
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/spotifyd.service"
    dest: ${HOME}/.config/systemd/user/spotifyd.service
- name: Ensure user's spotifyd config folder exists
  ansible.builtin.file:
    state: directory
    path: ${HOME}/.config/spotifyd/
- name: Copy configuration file
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/spotifyd.conf"
    dest: ${HOME}/.config/spotifyd/spotifyd.conf
- name: Reload systemd so service is available
  ansible.builtin.command:
    cmd: systemctl --user daemon-reload
- name: Start spotifyd on login
  ansible.builtin.command:
    cmd: systemctl --user enable --now spotifyd
- name: Force restart spotifyd
  ansible.builtin.command:
    cmd: systemctl --user restart spotifyd