---
- name: Install packages
  aur:
    name:
      - pulseaudio                  #
      - pulseaudio-alsa             #
      - pulsemixer                  #
      - alsa-utils                  #
      - mpv                         #