---
- name: Install packages
  yay:
    packages:
      - pulseaudio                      #
      - pulseaudio-alsa                 #
      - pulsemixer                      #
      - alsa-utils                      #
      - mpv                             #