---
- name: install packages
  yay:
    packages:
      - awesome-git                     #
      - rofi                            #
      - picom                           #
- name: copy awesome config
  copy:
    src: awesome/
    dest: ${HOME}/.config/awesome/
- name: Copy rofi config
  ansible.builtin.copy:
    src: rofi/
    dest: ${HOME}/.config/rofi/