---
- name: Install font packages
  yay:
    packages:
      - ttf-font-awesome
      - ttf-anonymous-pro
      - noto-fonts
      - adobe-source-code-pro-fonts
      - ttf-inconsolata
      - ttf-linux-libertine
      - ttf-unifont
- name: fontconfig dir
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/fontconfig"
    dest: ${HOME}/.config/fontconfig
- name: font files
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/fonts"
    dest: ${HOME}/.local/share/fonts
- name: reset font cache
  ansible.builtin.command:
    cmd: fc-cache -f -v
