- name: Install packages
  apt:
    pkg: git

- name: gitconfig
  copy:
    src: gitconfig
    dest: "${HOME}/.git/config"

- name: gitignore
  copy:
    src: gitignore
    dest: "${HOME}/.gitignore"