---
- name: Install packages
  yay:
    packages:
      - iptables                        # Firewall support used by Docker
      - docker                          # What if we virtualized the virtualization layer?
      - lens-bin                        # The Kubernetes IDE
- name: Manage kubectl versions
  asdf:
    name: kubectl
    global_version: 1.20.7
    versions:
      - 1.18.19
      - 1.19.11
      - 1.20.7
- name: Manage helm versions
  asdf:
    name: helm
    global_version: 3.6.0
    versions:
      - 3.5.4
      - 3.6.0