---
- name: Install package
  yay:
    packages: neovim
- name: link neovim configuration
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/neovim"
    dest: ${HOME}/.config/neovim