---
- name: install packages
  yay:
    packages:
      - awesome-git                     #
      - rofi                            #
      - picom                           #
- name: link awesome configuration
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/awesome"
    dest: ${HOME}/.config/awesome
- name: link rofi configuration
  ansible.builtin.copy:
    src: rofi/
    dest: ${HOME}/.config/rofi/
- name: Ensure picom config exists
  ansible.builtin.file:
    state: directory
    path: ${HOME}/.config/picom/
- name: link picom configuration
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/picom/picom.conf"
    dest: ${HOME}/.config/picom/picom.conf