---
- name: Install packages
  yay:
    packages:
      - gnome-keyring
- name: Setup pam.d login file
  ansible.builtin.copy:
    src: pamd-login
    dest: /etc/pam.d/login
  become: yes
- name: Setup pam.d passwd file
  ansible.builtin.copy:
    src: pamd-passwd
    dest: /etc/pam.d/passwd
  become: yes