[global]
username = "sunspar"
use_keyring = true
backend = "alsa"
device = "sysdefault" # Given by `aplay -L`, can also change it to always push to a specific device
mixer = "PCM"
volume-controller = "alsa" # or alsa_linear, or softvol
#onevent = command_run_on_playback_event
device_name = "spotifyd"
bitrate = 320
cache_path = "cache_directory"
volume-normalisation = true
normalisation-pregain = -10